import './globals.css'
import { Inter } from 'next/font/google'
import '@fortawesome/fontawesome-free/css/fontawesome.css';
import '@fortawesome/fontawesome-free/css/brands.css';
import 'bootstrap/dist/css/bootstrap.css';
import '@fortawesome/fontawesome-svg-core/styles.css';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portifólio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link href="https://fonts.googleapis.com/css2?family=Anton&family=Merriweather&family=Passion+One&family=REM:ital,wght@1,700&family=Roboto&family=Rubik+Mono+One&display=swap" rel="stylesheet">
      </link>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
